[
 {
   "Product Id": "",
   "Product Handle": "coffee-mug-v3",
   "Product Title": "Medusa Coffee Mug",
   "Product Subtitle": "",
   "Product Description": "Every programmer's best friend.",
   "Product Status": "published",
   "Product Thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/coffee-mug.png",
   "Product Weight": 400,
   "Product Length": "",
   "Product Width": "",
   "Product Height": "",
   "Product HS Code": "",
   "Product Origin Country": "",
   "Product MID Code": "",
   "Product Material": "",
   "Shipping Profile Id": "",
   "Product Sales Channel 1": "",
   "Product Collection Id": "",
   "Product Type Id": "",
   "Product Tag 1": "",
   "Product Discountable": true,
   "Product External Id": "",
   "Variant Id": "",
   "Variant Title": "One Size",
   "Variant SKU": "",
   "Variant Barcode": "",
   "Variant Allow Backorder": false,
   "Variant Manage Inventory": true,
   "Variant Weight": "",
   "Variant Length": "",
   "Variant Width": "",
   "Variant Height": "",
   "Variant HS Code": "",
   "Variant Origin Country": "",
   "Variant MID Code": "",
   "Variant Material": "",
   "Variant Price EUR": 10,
   "Variant Price USD": 12,
   "Variant Option 1 Name": "Size",
   "Variant Option 1 Value": "One Size",
   "Product Image 1 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/coffee-mug.png",
   "Product Image 2 Url": ""
 },
 {
   "Product Id": "",
   "Product Handle": "sweatpants-v2",
   "Product Title": "Medusa Sweatpants",
   "Product Subtitle": "",
   "Product Description": "Reimagine the feeling of classic sweatpants. With our cotton sweatpants, everyday essentials no longer have to be ordinary.",
   "Product Status": "published",
   "Product Thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Weight": 400,
   "Product Length": "",
   "Product Width": "",
   "Product Height": "",
   "Product HS Code": "",
   "Product Origin Country": "",
   "Product MID Code": "",
   "Product Material": "",
   "Shipping Profile Id": "",
   "Product Sales Channel 1": "",
   "Product Collection Id": "",
   "Product Type Id": "",
   "Product Tag 1": "",
   "Product Discountable": true,
   "Product External Id": "",
   "Variant Id": "",
   "Variant Title": "S",
   "Variant SKU": "",
   "Variant Barcode": "",
   "Variant Allow Backorder": false,
   "Variant Manage Inventory": true,
   "Variant Weight": "",
   "Variant Length": "",
   "Variant Width": "",
   "Variant Height": "",
   "Variant HS Code": "",
   "Variant Origin Country": "",
   "Variant MID Code": "",
   "Variant Material": "",
   "Variant Price EUR": 29.5,
   "Variant Price USD": 33.5,
   "Variant Option 1 Name": "Size",
   "Variant Option 1 Value": "S",
   "Product Image 1 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Image 2 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-back.png"
 },
 {
   "Product Id": "",
   "Product Handle": "sweatpants-v2",
   "Product Title": "Medusa Sweatpants",
   "Product Subtitle": "",
   "Product Description": "Reimagine the feeling of classic sweatpants. With our cotton sweatpants, everyday essentials no longer have to be ordinary.",
   "Product Status": "published",
   "Product Thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Weight": 400,
   "Product Length": "",
   "Product Width": "",
   "Product Height": "",
   "Product HS Code": "",
   "Product Origin Country": "",
   "Product MID Code": "",
   "Product Material": "",
   "Shipping Profile Id": "",
   "Product Sales Channel 1": "",
   "Product Collection Id": "",
   "Product Type Id": "",
   "Product Tag 1": "",
   "Product Discountable": true,
   "Product External Id": "",
   "Variant Id": "",
   "Variant Title": "M",
   "Variant SKU": "",
   "Variant Barcode": "",
   "Variant Allow Backorder": false,
   "Variant Manage Inventory": true,
   "Variant Weight": "",
   "Variant Length": "",
   "Variant Width": "",
   "Variant Height": "",
   "Variant HS Code": "",
   "Variant Origin Country": "",
   "Variant MID Code": "",
   "Variant Material": "",
   "Variant Price EUR": 29.5,
   "Variant Price USD": 33.5,
   "Variant Option 1 Name": "Size",
   "Variant Option 1 Value": "M",
   "Product Image 1 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Image 2 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-back.png"
 },
 {
   "Product Id": "",
   "Product Handle": "sweatpants-v2",
   "Product Title": "Medusa Sweatpants",
   "Product Subtitle": "",
   "Product Description": "Reimagine the feeling of classic sweatpants. With our cotton sweatpants, everyday essentials no longer have to be ordinary.",
   "Product Status": "published",
   "Product Thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Weight": 400,
   "Product Length": "",
   "Product Width": "",
   "Product Height": "",
   "Product HS Code": "",
   "Product Origin Country": "",
   "Product MID Code": "",
   "Product Material": "",
   "Shipping Profile Id": "",
   "Product Sales Channel 1": "",
   "Product Collection Id": "",
   "Product Type Id": "",
   "Product Tag 1": "",
   "Product Discountable": true,
   "Product External Id": "",
   "Variant Id": "",
   "Variant Title": "L",
   "Variant SKU": "",
   "Variant Barcode": "",
   "Variant Allow Backorder": false,
   "Variant Manage Inventory": true,
   "Variant Weight": "",
   "Variant Length": "",
   "Variant Width": "",
   "Variant Height": "",
   "Variant HS Code": "",
   "Variant Origin Country": "",
   "Variant MID Code": "",
   "Variant Material": "",
   "Variant Price EUR": 29.5,
   "Variant Price USD": 33.5,
   "Variant Option 1 Name": "Size",
   "Variant Option 1 Value": "L",
   "Product Image 1 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Image 2 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-back.png"
 },
 {
   "Product Id": "",
   "Product Handle": "sweatpants-v2",
   "Product Title": "Medusa Sweatpants",
   "Product Subtitle": "",
   "Product Description": "Reimagine the feeling of classic sweatpants. With our cotton sweatpants, everyday essentials no longer have to be ordinary.",
   "Product Status": "published",
   "Product Thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Weight": 400,
   "Product Length": "",
   "Product Width": "",
   "Product Height": "",
   "Product HS Code": "",
   "Product Origin Country": "",
   "Product MID Code": "",
   "Product Material": "",
   "Shipping Profile Id": "",
   "Product Sales Channel 1": "",
   "Product Collection Id": "",
   "Product Type Id": "",
   "Product Tag 1": "",
   "Product Discountable": true,
   "Product External Id": "",
   "Variant Id": "",
   "Variant Title": "XL",
   "Variant SKU": "",
   "Variant Barcode": "",
   "Variant Allow Backorder": false,
   "Variant Manage Inventory": true,
   "Variant Weight": "",
   "Variant Length": "",
   "Variant Width": "",
   "Variant Height": "",
   "Variant HS Code": "",
   "Variant Origin Country": "",
   "Variant MID Code": "",
   "Variant Material": "",
   "Variant Price EUR": 29.5,
   "Variant Price USD": 33.5,
   "Variant Option 1 Name": "Size",
   "Variant Option 1 Value": "XL",
   "Product Image 1 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
   "Product Image 2 Url": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-back.png"
 }
]